-- ============================================================
-- Twostones Studio — Full PostgreSQL Schema for Supabase
-- Paste this entire file into the Supabase SQL Editor and run.
-- ============================================================

-- 1. Create Enum Types (Idempotent)
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_users_role') THEN
        CREATE TYPE enum_users_role AS ENUM ('customer', 'admin');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_carts_status') THEN
        CREATE TYPE enum_carts_status AS ENUM ('active', 'completed', 'abandoned');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_orders_status') THEN
        CREATE TYPE enum_orders_status AS ENUM ('pending', 'paid', 'shipped', 'delivered', 'cancelled');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_orders_payment_status') THEN
        CREATE TYPE enum_orders_payment_status AS ENUM ('unpaid', 'paid', 'refunded');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_orders_payment_method') THEN
        CREATE TYPE enum_orders_payment_method AS ENUM ('manual', 'mpesa', 'card');
    END IF;
END $$;

-- 2. Users
CREATE TABLE IF NOT EXISTS "Users" (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT NOT NULL,
    email        TEXT NOT NULL UNIQUE,
    password     TEXT NOT NULL,
    role         enum_users_role DEFAULT 'customer',
    measurements JSONB DEFAULT '{"bust":"","waist":"","hips":"","shoulder":"","armhole":"","inseam":"","height":"","notes":""}',
    "createdAt"  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updatedAt"  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Categories
CREATE TABLE IF NOT EXISTS "Categories" (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT NOT NULL UNIQUE,
    description  TEXT,
    slug         TEXT NOT NULL UNIQUE,
    "createdAt"  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updatedAt"  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. Products
CREATE TABLE IF NOT EXISTS "Products" (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT NOT NULL,
    description     TEXT NOT NULL,
    price           NUMERIC(10,2) NOT NULL,
    sku             TEXT NOT NULL UNIQUE,
    stock_quantity  INTEGER DEFAULT 0,
    category_id     INTEGER NOT NULL REFERENCES "Categories"(id) ON DELETE CASCADE ON UPDATE CASCADE,
    is_active       BOOLEAN DEFAULT TRUE,
    "createdAt"     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updatedAt"     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. ProductImages
CREATE TABLE IF NOT EXISTS "ProductImages" (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id   INTEGER NOT NULL REFERENCES "Products"(id) ON DELETE CASCADE ON UPDATE CASCADE,
    image_url    TEXT NOT NULL,
    is_primary   BOOLEAN DEFAULT FALSE,
    "createdAt"  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updatedAt"  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6. Carts
CREATE TABLE IF NOT EXISTS "Carts" (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INTEGER REFERENCES "Users"(id) ON DELETE SET NULL ON UPDATE CASCADE,
    status       enum_carts_status DEFAULT 'active',
    "createdAt"  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updatedAt"  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 7. CartItems
CREATE TABLE IF NOT EXISTS "CartItems" (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id      INTEGER NOT NULL REFERENCES "Carts"(id) ON DELETE CASCADE ON UPDATE CASCADE,
    product_id   TEXT NOT NULL,
    quantity     INTEGER NOT NULL DEFAULT 1,
    "createdAt"  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updatedAt"  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 8. Orders
CREATE TABLE IF NOT EXISTS "Orders" (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          INTEGER NOT NULL REFERENCES "Users"(id) ON DELETE CASCADE ON UPDATE CASCADE,
    total_amount     NUMERIC(10,2) NOT NULL,
    status           enum_orders_status DEFAULT 'pending',
    payment_status   enum_orders_payment_status DEFAULT 'unpaid',
    shipping_address TEXT NOT NULL,
    payment_method   enum_orders_payment_method DEFAULT 'manual',
    customer_email   TEXT,
    customer_phone   TEXT,
    "createdAt"      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updatedAt"      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 9. OrderItems
CREATE TABLE IF NOT EXISTS "OrderItems" (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id          INTEGER NOT NULL REFERENCES "Orders"(id) ON DELETE CASCADE ON UPDATE CASCADE,
    product_id        TEXT NOT NULL,
    quantity          INTEGER NOT NULL,
    price_at_purchase NUMERIC(10,2) NOT NULL,
    "createdAt"       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updatedAt"       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 10. JournalEntries
CREATE TABLE IF NOT EXISTS "JournalEntries" (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_number       INTEGER NOT NULL UNIQUE,
    title            TEXT NOT NULL,
    encounter_text   TEXT NOT NULL,
    strengths        TEXT,
    weaknesses       TEXT,
    modern_contrast  TEXT,
    identity_text    TEXT,
    lie_text         TEXT,
    truth_text       TEXT,
    consequence_text TEXT,
    redemption_text  TEXT,
    reflective_question TEXT,
    image_url        TEXT,
    biblical_ref     TEXT,
    subtitle         TEXT,
    is_free          BOOLEAN DEFAULT TRUE,
    garment_id       INTEGER REFERENCES "Products"(id) ON DELETE SET NULL ON UPDATE CASCADE,
    "createdAt"      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updatedAt"      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 11. JournalResponses
CREATE TABLE IF NOT EXISTS "JournalResponses" (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INTEGER NOT NULL REFERENCES "Users"(id) ON DELETE CASCADE ON UPDATE CASCADE,
    entry_id        INTEGER NOT NULL REFERENCES "JournalEntries"(id) ON DELETE CASCADE ON UPDATE CASCADE,
    reflection_text TEXT NOT NULL,
    "createdAt"     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updatedAt"     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 12. ManukatoItems
CREATE TABLE IF NOT EXISTS "ManukatoItems" (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "originalName"  TEXT NOT NULL UNIQUE,
    "imagePath"     TEXT NOT NULL,
    "brandName"     TEXT,
    description     TEXT,
    "stylingTips"   TEXT,
    price           NUMERIC(10,2),
    "isActive"      BOOLEAN DEFAULT TRUE,
    "showInShop"    BOOLEAN DEFAULT TRUE,
    "createdAt"     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updatedAt"     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
