const { uploadFile } = require('../src/utils/storage');
const path = require('path');
const fs = require('fs');
const dns = require('dns');

if (dns.setDefaultResultOrder) {
    dns.setDefaultResultOrder('ipv4first');
}

const BUCKET_NAME = 'manukato';

// The images previously generated by the AI
const filesToUpload = [
    { day: 1, name: 'eve', path: 'C:\\Users\\USER PC\\.gemini\\antigravity\\brain\\64624f61-7938-4a35-8287-9bedda4b7406\\day1_eve_couture_1772279453939.png' },
    { day: 2, name: 'sarah', path: 'C:\\Users\\USER PC\\.gemini\\antigravity\\brain\\64624f61-7938-4a35-8287-9bedda4b7406\\day2_sarah_couture_1772279473754.png' },
    { day: 3, name: 'hagar', path: 'C:\\Users\\USER PC\\.gemini\\antigravity\\brain\\64624f61-7938-4a35-8287-9bedda4b7406\\day3_hagar_couture_1772279493870.png' },
    { day: 4, name: 'lots_wife', path: 'C:\\Users\\USER PC\\.gemini\\antigravity\\brain\\64624f61-7938-4a35-8287-9bedda4b7406\\day4_lots_wife_couture_1772279510280.png' },
    { day: 5, name: 'rebekah', path: 'C:\\Users\\USER PC\\.gemini\\antigravity\\brain\\64624f61-7938-4a35-8287-9bedda4b7406\\day5_rebekah_couture_1772279525964.png' },
    { day: 6, name: 'leah', path: 'C:\\Users\\USER PC\\.gemini\\antigravity\\brain\\64624f61-7938-4a35-8287-9bedda4b7406\\day6_leah_couture_1772279568313.png' }
];

async function uploadBatch() {
    console.log('Starting upload of 6 custom journal images...');
    const uploadedUrls = {};
    for (const file of filesToUpload) {
        if (fs.existsSync(file.path)) {
            try {
                const targetPath = `journal/day${file.day}_${file.name}.png`;
                const url = await uploadFile(file.path, BUCKET_NAME, targetPath);
                console.log(`✅ Success for Day ${file.day} (${file.name}):`, url);
                uploadedUrls[file.day] = url;
            } catch (err) {
                console.error(`❌ Failed Day ${file.day}:`, err.message);
            }
        } else {
            console.log(`⚠️ Not found locally: ${file.path}`);
        }
    }

    fs.writeFileSync(path.join(__dirname, 'batch1_urls.json'), JSON.stringify(uploadedUrls, null, 2));
    console.log('URLs saved to batch1_urls.json');
    process.exit(0);
}

uploadBatch();
